// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kpafmbvijbfdvhsbffah.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtwYWZtYnZpamJmZHZoc2JmZmFoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU3NjkyMjIsImV4cCI6MjA2MTM0NTIyMn0.aNCsoqsFcwY5A6UBdB_RE5PVARbyafUdyAj_aw4cmzE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);